name: ESP-IDF Build Multiple Projects (Docker)

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - TCS-Mini/TCSDG-TCS-Mini-LoRa
          - TCS-Master/TCSDG-TCS-Master-Main

    container:
      image: espressif/idf:v5.4

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      # 2. Build project
      - name: Build project
        run: idf.py build
        working-directory: ${{ matrix.project }}

      # 3. Upload binaries
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.project }}
          path: |
            ${{ matrix.project }}/build/*.bin
            ${{ matrix.project }}/build/*.elf

      # 4. Clean up build folder
      - name: Clean up build folder
        run: rm -rf ${{ matrix.project }}/build
